version: "2.1"

networks:
  internal_network:

services:
  kibana:
    image: kibana:7.8.0
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - internal_network
    ports:
      - 5601:5601

  elasticsearch:
    build: ./elasticsearch
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - internal_network
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ${PWD}/data:/usr/share/elasticsearch/data
  
  indexer-blueleaks:
    build: ./indexer
    environment:
      - COLLECTION=blueleaks
      - INPUT=/data
      - ELASTICSEARCH=http://elasticsearch:9200
    volumes:
      - ${PWD}/BlueLeaks:/data
    networks: 
      - internal_network
